version: '3'
services:
 bitcoindev:
  build: BitcoinDev
  image: bitcoindev
 bitcoinClient:
  build: ClientBaseImage
  image: bitcoinnode
 a:
  build: MasterBaseImage
  image: bitcoinmnode
  ports:
   - 20000:18332
  depends_on:
  - bitcoindev
 b35fe16e-9b9b-470d-9404-ba56fe9eb960:
  image: bitcoinnode
  ports:
   - 20001:18332
  networks:
   - mybitcoinnetwork
  deploy:
   restart_policy:
     condition: on-failure
  depends_on:
   - a
 0d0c44da-169a-41ec-8546-5b0ff9485712:
  image: bitcoinnode
  ports:
   - 20002:18332
  networks:
   - mybitcoinnetwork
  deploy:
   restart_policy:
     condition: on-failure
  depends_on:
   - a
 f621bfa9-7bdd-4def-99e0-1dcf41dcc533:
  image: bitcoinnode
  ports:
   - 20003:18332
  networks:
   - mybitcoinnetwork
  deploy:
   restart_policy:
     condition: on-failure
  depends_on:
   - a
 aec37275-1b6f-44c3-9ace-9fd71edc32a0:
  image: bitcoinnode
  ports:
   - 20004:18332
  networks:
   - mybitcoinnetwork
  deploy:
   restart_policy:
     condition: on-failure
  depends_on:
   - a
 9f2019c6-f217-489b-9a76-0176e813b2c1:
  image: bitcoinnode
  ports:
   - 20005:18332
  networks:
   - mybitcoinnetwork
  deploy:
   restart_policy:
     condition: on-failure
  depends_on:
   - a
 7d7f284d-31da-4708-b2b4-cd18dd24cd80:
  image: bitcoinnode
  ports:
   - 20006:18332
  networks:
   - mybitcoinnetwork
  deploy:
   restart_policy:
     condition: on-failure
  depends_on:
   - a
 cb829dfe-df6d-4617-889f-65cdbbf113d4:
  image: bitcoinnode
  ports:
   - 20007:18332
  networks:
   - mybitcoinnetwork
  deploy:
   restart_policy:
     condition: on-failure
  depends_on:
   - a
 426073b7-de44-45e5-a788-a2f176a1dd07:
  image: bitcoinnode
  ports:
   - 20008:18332
  networks:
   - mybitcoinnetwork
  deploy:
   restart_policy:
     condition: on-failure
  depends_on:
   - a
 b319a01b-5701-4b98-a231-23d25e89c88b:
  image: bitcoinnode
  ports:
   - 20009:18332
  networks:
   - mybitcoinnetwork
  deploy:
   restart_policy:
     condition: on-failure
  depends_on:
   - a
 6b69c2e3-b640-42f5-be75-9f49308f9e44:
  image: bitcoinnode
  ports:
   - 20010:18332
  networks:
   - mybitcoinnetwork
  deploy:
   restart_policy:
     condition: on-failure
  depends_on:
   - a
networks:
 mybitcoinnetwork:
  external:
    name: mybitcoin