version: '2'
services:
 bitcoindev:
  build: BitcoinDev
  image: bitcoindev

 a:
  build: MasterBaseImage
  image: bitcoinmnode
  ports:
   - 20000:18332
  depends_on:
  - bitcoindev
  
 b:
  build: ClientBaseImage
  image: bitcoinnode
  ports:
   - 20001:18332
  depends_on:
   - a
  links:
   - a
  
 c:
  image: bitcoinnode
  ports:
   - 20002:18332
  depends_on:
   - a
  links:
   - a

 d:
  image: bitcoinnode
  ports:
   - 20003:18332
  depends_on:
   - a
  links:
   - a

 e:
  image: bitcoinnode
  ports:
   - 20004:18332
  depends_on:
   - a
  links:
   - a

 f:
  image: bitcoinnode
  ports:
   - 20005:18332
  depends_on:
   - a
  links:
   - a

 g:
  image: bitcoinnode
  ports:
   - 20006:18332
  depends_on:
   - a
  links:
   - a

 h:
  image: bitcoinnode
  ports:
   - 20007:18332
  depends_on:
   - a
  links:
   - a

 i:
  image: bitcoinnode
  ports:
   - 20008:18332
  depends_on:
   - a
  links:
   - a

 j:
  image: bitcoinnode
  ports:
   - 20009:18332
  depends_on:
   - a
  links:
   - a
