version: '3'
services:
 bitcoindev:
  build: BitcoinDev
  image: bitcoindev
 bitcoinClient:
  build: ClientBaseImage
  image: bitcoinnode
 a:
  build: MasterBaseImage
  image: bitcoinmnode
  ports:
   - 19000:18444
   - 20000:18332
  depends_on:
  - bitcoindev
  networks:
  - mybitcoinnetwork
 0f12c283-9bf1-4135-864c-b33af3c70fd7:
  image: bitcoinnode
  ports:
   - 19001:18444
   - 20001:18332
  networks:
   - mybitcoinnetwork
  deploy:
   restart_policy:
     condition: on-failure
  depends_on:
   - a
 456f0dd0-97dd-42d4-9678-864bf7f9556b:
  image: bitcoinnode
  ports:
   - 19002:18444
   - 20002:18332
  networks:
   - mybitcoinnetwork
  deploy:
   restart_policy:
     condition: on-failure
  depends_on:
   - a
networks:
 mybitcoinnetwork:
  external:
    name: mybitcoin