version: '2'
services:
 bob:
  build: bob
  ports:
   - 18444:18444
   - 18332:18332
  
 alice:
  image: bitcoin:v0.14
  ports:
   - 19444:18444
   - 19332:18332
  depends_on:
   - bob
  links:
   - bob
  
 henry:
  image: bitcoin:v0.14
  ports:
   - 17444:18444
   - 17332:18332
  depends_on:
   - bob
  links:
   - bob

 charlie:
  image: bitcoin:v0.14
  ports:
   - 20444:18444
   - 20332:18332
  depends_on:
   - bob
  links:
   - bob


  
