version: '3'
services:
 bitcoindev:
  build: BitcoinDev
  image: bitcoindev
 bitcoinClient:
  build: ClientBaseImage
  image: bitcoinnode
 a:
  build: MasterBaseImage
  image: bitcoinmnode
  ports:
   - 19000:18444
   - 20000:18332
  depends_on:
  - bitcoindev
  networks:
   - mybitcoinnetwork
 6a8cbd35-a209-4261-b017-57fa4685a6be:
  image: bitcoinnode
  ports:
   - 19001:18444
   - 20001:18332
  networks:
   - mybitcoinnetwork
  deploy:
   restart_policy:
     condition: on-failure
  depends_on:
   - a
 6cd933d6-5d91-4265-95ac-6199f891d820:
  image: bitcoinnode
  ports:
   - 19002:18444
   - 20002:18332
  networks:
   - mybitcoinnetwork
  deploy:
   restart_policy:
     condition: on-failure
  depends_on:
   - a
networks:
 mybitcoinnetwork:
  external:
    name: mybitcoin
